name: Terraform Route53 Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -var="domain_name=yourdomain.com"
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="domain_name=yourdomain.com"
        working-directory: terraform
